package streameditor;

import javax.swing.*;
import java.awt.*;

public class GuiTerminal {
    private JPanel MainPanel;
    private JTextArea textArea1;
    private JComboBox<String> comboBox1;

    public GuiTerminal() {
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("GuiTerminal");
        frame.setContentPane(new GuiTerminal().MainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        MainPanel = new JPanel();
        MainPanel.setLayout(new BorderLayout(0, 0));
        final JScrollPane scrollPane1 = new JScrollPane();
        MainPanel.add(scrollPane1, BorderLayout.CENTER);
        scrollPane1.setViewportView(textArea1);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setAutoscrolls(true);
        panel1.setBackground(new Color(-14605013));
        panel1.setPreferredSize(new Dimension(0, 25));
        MainPanel.add(panel1, BorderLayout.SOUTH);
        comboBox1.setEditable(true);
        comboBox1.setMinimumSize(new Dimension(200, 100));
        comboBox1.setPreferredSize(new Dimension(200, 100));
        panel1.add(comboBox1, BorderLayout.WEST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }

    private void createUIComponents() {
        comboBox1 = new JComboBox<>();
        textArea1 = new StreamingTextArea(comboBox1);
    }
}
